// Page registry: maps pageId → route (+ optional tab)
// Used by smart search to navigate when a result is selected.

export const SMART_SEARCH_PAGES: Record<string, { route: string; tab?: string }> = {
  dashboard:           { route: '/',                    tab: undefined },
  activity:            { route: '/activity',             tab: undefined },
  'activity-apps':       { route: '/activity',             tab: 'apps' },
  'activity-websites':   { route: '/activity',             tab: 'websites' },
  'activity-productivity':{ route: '/activity',            tab: 'productivity' },
  'activity-focus':      { route: '/activity',             tab: 'focus' },
  rankings:            { route: '/rankings' },
  'ide-overview':        { route: '/ide',                 tab: 'overview' },
  'ide-environment':     { route: '/ide',                 tab: 'environment' },
  'ide-projects':        { route: '/ide',                 tab: 'projects' },
  'ide-git':             { route: '/ide',                 tab: 'git' },
  'ide-analytics':       { route: '/ide',                 tab: 'analytics' },
  'ide-backup':          { route: '/ide',                 tab: 'backup' },
  'ide-ai-tools':        { route: '/ide',                 tab: 'ai' },
  terminal:            { route: '/terminal' },
  'terminal-setup':      { route: '/terminal',            tab: 'setup' },
  'terminal-work':       { route: '/terminal',            tab: 'work' },
  'terminal-insights':   { route: '/terminal',            tab: 'insights' },
  'terminal-studio':     { route: '/terminal',            tab: 'studio' },
  'terminal-conductor':  { route: '/terminal',            tab: 'conductor' },
  'terminal-context':    { route: '/terminal',            tab: 'context' },
  life:                { route: '/life' },
  'life-phases':         { route: '/life' },
  'life-river':          { route: '/life' },
  'life-gold':           { route: '/life' },
  learn:               { route: '/learn' },
  'learn-courses':       { route: '/learn' },
  'learn-deck':          { route: '/learn' },
  ai:                  { route: '/ai' },
  'ai-chat':             { route: '/ai' },
  'ai-canvas':           { route: '/ai',                 tab: 'canvas' },
  'ai-daily-planner':    { route: '/ai' },
  'ai-weekly-schedule':  { route: '/ai' },
  'ai-deadline-tracker': { route: '/ai' },
  'ai-compositions':     { route: '/ai',                 tab: 'compositions' },
  'ai-tools':            { route: '/ai' },
  studio:              { route: '/studio' },
  'studio-overlay':      { route: '/studio' },
  'studio-templates':    { route: '/studio' },
  finance:             { route: '/finance' },
  'finance-overview':    { route: '/finance',            tab: 'overview' },
  'finance-wallets':     { route: '/finance',            tab: 'wallets' },
  'finance-transactions':{ route: '/finance',            tab: 'transactions' },
  'finance-categories':  { route: '/finance',            tab: 'categories' },
  'finance-people':      { route: '/finance',            tab: 'people' },
  'finance-budget':      { route: '/finance',            tab: 'budget' },
  'finance-charts':      { route: '/finance',            tab: 'charts' },
  'finance-subscriptions':{ route: '/finance',           tab: 'subscriptions' },
  'finance-audit':       { route: '/finance',            tab: 'audit' },
  'finance-recap':       { route: '/finance',            tab: 'recap' },
  resume:              { route: '/resume' },
  'resume-build':        { route: '/resume/build' },
  'resume-preview':      { route: '/resume/preview' },
  'resume-import':       { route: '/resume/import' },
  'resume-export':       { route: '/resume/export' },
  external:            { route: '/external' },
  'external-manual':     { route: '/external' },
  'external-list':       { route: '/external' },
  reports:             { route: '/reports' },
  'insights-day':        { route: '/reports',            tab: 'typical' },
  'insights-weekly':     { route: '/reports',            tab: 'weekly' },
  'insights-activities': { route: '/reports',            tab: 'activities' },
  'insights-recap':      { route: '/reports',            tab: 'recap' },
  database:            { route: '/database' },
  'database-browse':     { route: '/database',           tab: 'browse' },
  'database-architecture':{ route: '/database',          tab: 'architecture' },
  'database-changes':    { route: '/database',           tab: 'changes' },
  guide:               { route: '/guide' },
  'guide-tutorial':      { route: '/guide',              tab: 'tutorial' },
  'guide-specs':         { route: '/guide',              tab: 'specs' },
  settings:            { route: '/settings' },
  'settings-appearance': { route: '/settings',           tab: 'appearance' },
  'settings-category':   { route: '/settings',           tab: 'category' },
  'settings-general':     { route: '/settings',           tab: 'general' },
  'settings-tracking':   { route: '/settings',           tab: 'tracking' },
  'settings-prompts':    { route: '/settings',           tab: 'prompts' },
  'settings-colors':     { route: '/settings',           tab: 'colors' },
  'settings-ai':         { route: '/settings',           tab: 'ai' },
  'settings-ai-diagnostics':{ route: '/settings',        tab: 'ai' },
  'settings-finance':    { route: '/settings',           tab: 'finance' },
  'settings-devices':    { route: '/settings',           tab: 'devices' },
  focus:               { route: '/focus' },
  'focus-goals':         { route: '/focus',              tab: 'goals' },
  'focus-stats':         { route: '/focus',              tab: 'stats' },
  'focus-history':       { route: '/focus',              tab: 'history' },
};

export function resolvePageRoute(pageId: string): { route: string; tab?: string } | null {
  return SMART_SEARCH_PAGES[pageId] ?? null;
}
