import type { ProviderTemplate } from './types';

export const PROVIDER_TEMPLATES: Record<string, ProviderTemplate> = {
  openrouter: {
    id: 'openrouter',
    label: 'OpenRouter',
    defaultBaseUrl: 'https://openrouter.ai/api/v1/chat/completions',
    auth: { type: 'bearer' },
    staticHeaders: { 'HTTP-Referer': 'https://deskflow.app', 'X-Title': 'DeskFlow' },
    suggestedModels: ['google/gemini-2.0-flash-001', 'deepseek/deepseek-chat-v3-0324'],
    docsUrl: 'https://openrouter.ai/docs',
    supportsStream: true,
  },
  cloudflare: {
    id: 'cloudflare',
    label: 'Cloudflare',
    defaultBaseUrl: 'https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1/chat/completions',
    auth: { type: 'bearer' },
    staticHeaders: { 'Content-Type': 'application/json' },
    suggestedModels: ['@cf/meta/llama-3.1-8b-instruct', '@cf/mistral/mistral-7b-instruct-v0.1'],
    docsUrl: 'https://developers.cloudflare.com/workers-ai/',
    interpolateUrl: (url, config) => url.replace('{account_id}', config.extraConfig?.cloudflareAccountId || '{account_id}'),
    parseResponse: (raw: any) => ({
      content: raw.result?.response || raw.choices?.[0]?.message?.content || '',
      usage: raw.result?.usage || raw.usage,
    }),
    supportsStream: false,
  },
  ollama: {
    id: 'ollama',
    label: 'Ollama',
    defaultBaseUrl: 'http://localhost:11434/v1/chat/completions',
    auth: { type: 'bearer' },
    suggestedModels: ['llama3.1', 'qwen2.5', 'qwen2.5-vl:3b'],
    supportsStream: true,
  },
  github: {
    id: 'github',
    label: 'GitHub Models',
    defaultBaseUrl: 'https://models.inference.ai.azure.com/chat/completions',
    auth: { type: 'bearer' },
    staticHeaders: { 'Accept': 'application/json' },
    suggestedModels: ['gpt-4o-mini', 'gpt-4o', 'DeepSeek-V3', 'Mistral-large', 'Llama-3.1-70B'],
    docsUrl: 'https://docs.github.com/github-models',
    supportsStream: true,
  },
  google: {
    id: 'google',
    label: 'Google Gemini',
    defaultBaseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai/chat/completions',
    auth: { type: 'bearer' },
    suggestedModels: ['gemini-2.5-flash', 'gemini-2.5-pro', 'gemini-2.0-flash', 'gemini-2.0-flash-lite'],
    docsUrl: 'https://ai.google.dev/gemini-api/docs/quickstart',
    supportsStream: true,
  },
  custom: {
    id: 'custom',
    label: 'Custom (OpenAI-compatible)',
    defaultBaseUrl: '',
    auth: { type: 'bearer' },
    suggestedModels: [],
    supportsStream: true,
  },
};
